trigger:
- release
- dev

jobs:
- job: Linux
  timeoutInMinutes: 120
  pool:
    vmImage: 'Ubuntu-20.04'
  steps:
  - script: |
      sudo apt-get -qq update;
      sudo pip install --upgrade pip
      sudo apt-get install python-setuptools;
      sudo apt-get install libglew-dev libxrandr-dev libxcursor-dev libxinerama-dev libxi-dev;
      sudo pip install PySide2 ;
      sudo pip install PyOpenGL ;
      sudo python3 build_scripts/build_usd.py --no-materialx --build $HOME/USDgen/build --src $HOME/USDgen/src $HOME/USDinst -v
    displayName: 'Building USD'
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'usd-linux'
      targetPath: "/home/vsts/USDinst"
